export enum AUTH_NAV_SCREENS {
  SPLASH = 'SPLASH',
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
}

export enum BOTTOM_TAB_NAV_SCREENS {
  HOME = 'Home',
  CLAIM = 'Claim',
  BUY = 'Buy',
  INSURANCE = 'Insurance',
  ACCOUNT = 'Account',
}

export enum HOME_STACK_SCREENS {
  HOME_MAIN = 'HOME_MAIN',
}

export enum CLAIM_STACK_SCREENS {
  CLAIM_MAIN = 'CLAIM_MAIN',
  NEW_CLAIM = 'NEW_CLAIM',
  CLAIM_STATUS = 'CLAIM_STATUS',
}

export enum BUY_STACK_SCREENS {
  BUY_MAIN = 'BUY_MAIN',
}

export enum INSURANCE_STACK_SCREENS {
  INSURANCE_MAIN = 'INSURANCE_MAIN',
  POLICY_DETAILS = 'POLICY_DETAILS',
  RENEW_POLICY = 'RENEW_POLICY',
}

export enum ACCOUNT_STACK_SCREENS {
  ACCOUNT_MAIN = 'ACCOUNT_MAIN',
  SETTINGS = 'SETTINGS',
  PROFILE = 'PROFILE',
}
